# Generated by Django 4.1.2 on 2022-10-29 10:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='long_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='long_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='short_description'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='short_description'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='itemtagmodel',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='itemtagmodel',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
    ]
