# Generated by Django 4.1.2 on 2022-10-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_brandmodel_title_en_brandmodel_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantity'),
        ),
    ]
