# Generated by Django 4.1.2 on 2022-11-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_itemmodel_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmodel',
            name='quantity',
        ),
    ]
