# Generated by Django 4.1.2 on 2022-12-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_itemmodel_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandmodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='brandmodel',
            name='title_ru',
        ),
    ]
