# Generated by Django 4.1.2 on 2023-02-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_brandmodel_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='quantity'),
        ),
    ]
