# Generated by Django 4.1.2 on 2022-11-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordermodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantity'),
        ),
    ]
