# Generated by Django 4.1.2 on 2022-12-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordermodel_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='quantity',
        ),
    ]
